### ISSUE TITLE
A branch length probelm for the tree result files.

### ISSUE THREAD

**Issue by 544728460** [PavelTorgashov/FastTree#6]
I tried to use FastTree as a swift method to do phylogenetic analysis and it run without any error. But the tree result file seem abnormal for it genetic distance. Because almost for all branches, there seem no difference in branch length. The version of my FastTtree and the command I run are as follows:

command:
/opt/software/FastTreeMP -quote -boot 1000 -nt -gtr test.fasta > test_FastTreeoutcome.tree

version:
FastTree 2.1.11 SSE3, OpenMP (28 threads)

The screenshot of my problematic tree file is as follows:
![image](https://user-images.githubusercontent.com/50523037/110060110-5937ca80-7da0-11eb-9cbf-728fe7eccc97.png)

And the alignment file used to draw the phylogenetic tree is also attached.
[test.zip](https://github.com/PavelTorgashov/FastTree/files/6087867/test.zip)

**Comment by PavelTorgashov** [comment]
You are wrong with the repository. This repository is not related to FastTreeMP.
